### ISSUE TITLE
Issue building the plugin (undefined kafka.StringlyTypedACL)

### ISSUE THREAD

**Issue by cautious-bison** [Mongey/vault-plugin-secrets-kafka#1]
Hi,

I have the following error when building the plugin via the `bin/dev` script :
```
--> Building
# github.com/Mongey/vault-plugin-secrets-kafka/plugin
../src/github.com/Mongey/vault-plugin-secrets-kafka/plugin/path_list_roles.go:147:12: undefined: kafka.StringlyTypedACL
```

I already `go get github.com/Mongey/terraform-provider-kafka/kafka` as the structure comes from `terraform-provider-kafka/kafka/kafka_acls.go `

Is there another import I should be making ? Or another action rather than executing the dev script ?

Any hint would be useful.
Thx in advance.

**Comment by Mongey** [comment]
Hey @cautious-bison, sorry about that, I was using a non-master version of the `terraform-provider-kafka/kafka` package locally and haven't quite managed to get around to finishing the changes.

I've updated this repo to pull in the version I was using locally. If you pull from master you should be able to build the binary now.

**Comment by cautious-bison** [comment]
Hi,

Thx for the fix, it's working perfect.
I will try the plugin with a Kafka cluster.

Thx for open-sourcing this work.
